### ISSUE TITLE
Styling is not proper

### ISSUE THREAD

**Issue by Swapnil-2503** [Swapnil-2503/SwapSelf#1]
Need to style proper so user can go long with it. Also need to  make it responsive for all devices

**Comment by aishwarya-mali** [comment]
@Swapnil-2503 I'd like to work on this issue.

**Comment by Swapnil-2503** [comment]
Sure go for it, I will assign it to you

**Comment by aishwarya-mali** [comment]
@Swapnil-2503 Are you open for using any CSS framework like Bootstrap or Tailwind? or should I just use plain CSS?

**Comment by Swapnil-2503** [comment]
@aishwarya-mali Feel free to use the CSS framework (Bootstrap or Tailwind) that you find most comfortable and efficient for the project.
